package com.claudeexport;

import burp.api.montoya.BurpExtension;
import burp.api.montoya.MontoyaApi;
import burp.api.montoya.collaborator.CollaboratorClient;
import burp.api.montoya.core.ToolType;
import burp.api.montoya.http.handler.HttpHandler;
import burp.api.montoya.http.handler.HttpRequestToBeSent;
import burp.api.montoya.http.handler.HttpResponseReceived;
import burp.api.montoya.http.handler.RequestToBeSentAction;
import burp.api.montoya.http.handler.ResponseReceivedAction;

import javax.swing.*;
import java.awt.*;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Burp Suite extension that exports captured data (HTTP history, WebSockets history,
 * Repeater, Intruder, Target/Site map and Collaborator interactions) to a single
 * AI-friendly XML file.
 *
 * Design notes / limitations:
 *  - Proxy HTTP history, WebSocket history and the Target site map are read in full
 *    from the Montoya API at export time, regardless of when this extension was loaded.
 *  - Repeater / Intruder / Scanner traffic is NOT available retroactively through the
 *    Montoya API, so it is captured live through an HttpHandler from the moment this
 *    extension is loaded. Load it before working in those tools to capture everything.
 *  - Collaborator only exposes interactions for payloads generated by this extension's
 *    own Collaborator client (use the "Gerar payload" button).
 */
public class BurpClaudeExporter implements BurpExtension {

    static final String EXTENSION_NAME = "Claude XML Exporter";
    private static final int MAX_LIVE_RECORDS = 100_000;

    private MontoyaApi api;
    private final LiveTrafficCollector collector = new LiveTrafficCollector();
    private CollaboratorClient collaboratorClient;

    @Override
    public void initialize(MontoyaApi api) {
        this.api = api;
        api.extension().setName(EXTENSION_NAME);

        // Live capture of tool traffic that the API cannot read retroactively.
        api.http().registerHttpHandler(collector);

        // Best-effort Collaborator client (only sees its own payloads' interactions).
        try {
            collaboratorClient = api.collaborator().createClient();
        } catch (Exception e) {
            api.logging().logToError("Could not create Collaborator client: " + e.getMessage());
        }

        SwingUtilities.invokeLater(() -> {
            ExporterPanel panel = new ExporterPanel();
            api.userInterface().registerSuiteTab("Burp Export", panel);
        });

        api.logging().logToOutput(EXTENSION_NAME + " loaded. Live capture of Repeater/Intruder/Scanner is now active.");
    }

    // ------------------------------------------------------------------
    // UI
    // ------------------------------------------------------------------
    private class ExporterPanel extends JPanel {
        private final JCheckBox cbProxy = new JCheckBox("HTTP history (Proxy)", true);
        private final JCheckBox cbWebSocket = new JCheckBox("WebSockets history", true);
        private final JCheckBox cbRepeater = new JCheckBox("Repeater (captura ao vivo)", true);
        private final JCheckBox cbIntruder = new JCheckBox("Intruder (captura ao vivo)", true);
        private final JCheckBox cbOtherTools = new JCheckBox("Outras ferramentas (Scanner, Extensions...)", true);
        private final JCheckBox cbTarget = new JCheckBox("Target / Site map", true);
        private final JCheckBox cbCollaborator = new JCheckBox("Collaborator", true);
        private final JTextArea logArea = new JTextArea(12, 60);
        private final JLabel statusLabel = new JLabel("Pronto.");

        ExporterPanel() {
            setLayout(new BorderLayout(10, 10));
            setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

            JLabel title = new JLabel("Exportar dados do Burp para XML (análise por IA)");
            title.setFont(title.getFont().deriveFont(Font.BOLD, 16f));

            JPanel sources = new JPanel(new GridLayout(0, 1, 2, 2));
            sources.setBorder(BorderFactory.createTitledBorder("O que exportar"));
            sources.add(cbProxy);
            sources.add(cbWebSocket);
            sources.add(cbRepeater);
            sources.add(cbIntruder);
            sources.add(cbOtherTools);
            sources.add(cbTarget);
            sources.add(cbCollaborator);

            JButton exportBtn = new JButton("Exportar para XML...");
            exportBtn.addActionListener(e -> chooseAndExport());

            JButton collabBtn = new JButton("Gerar payload do Collaborator (copiar)");
            collabBtn.addActionListener(e -> generateCollaboratorPayload());

            JButton clearBtn = new JButton("Limpar captura ao vivo");
            clearBtn.addActionListener(e -> {
                collector.clear();
                appendLog("Captura ao vivo limpa.");
            });

            JPanel buttons = new JPanel(new FlowLayout(FlowLayout.LEFT));
            buttons.add(exportBtn);
            buttons.add(collabBtn);
            buttons.add(clearBtn);

            logArea.setEditable(false);
            logArea.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));
            JScrollPane logScroll = new JScrollPane(logArea);
            logScroll.setBorder(BorderFactory.createTitledBorder("Log"));

            JPanel north = new JPanel(new BorderLayout(6, 6));
            north.add(title, BorderLayout.NORTH);
            north.add(sources, BorderLayout.CENTER);
            north.add(buttons, BorderLayout.SOUTH);

            add(north, BorderLayout.NORTH);
            add(logScroll, BorderLayout.CENTER);
            add(statusLabel, BorderLayout.SOUTH);
        }

        private void generateCollaboratorPayload() {
            if (collaboratorClient == null) {
                appendLog("Collaborator indisponível nesta sessão.");
                return;
            }
            try {
                String payload = collaboratorClient.generatePayload().toString();
                Toolkit.getDefaultToolkit().getSystemClipboard()
                        .setContents(new StringSelection(payload), null);
                appendLog("Payload do Collaborator copiado: " + payload);
            } catch (Exception ex) {
                appendLog("Erro ao gerar payload: " + ex.getMessage());
            }
        }

        private void chooseAndExport() {
            JFileChooser chooser = new JFileChooser();
            String ts = ZonedDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss"));
            chooser.setSelectedFile(new File("burp-export-" + ts + ".xml"));
            if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
                return;
            }
            File file = chooser.getSelectedFile();

            ExportOptions options = new ExportOptions();
            options.proxy = cbProxy.isSelected();
            options.webSocket = cbWebSocket.isSelected();
            options.repeater = cbRepeater.isSelected();
            options.intruder = cbIntruder.isSelected();
            options.otherTools = cbOtherTools.isSelected();
            options.target = cbTarget.isSelected();
            options.collaborator = cbCollaborator.isSelected();

            statusLabel.setText("Exportando...");
            appendLog("Iniciando exportação para: " + file.getAbsolutePath());

            new Thread(() -> {
                try {
                    XmlExporter exporter = new XmlExporter(api, collector, collaboratorClient);
                    XmlExporter.Stats stats = exporter.export(file, options);
                    SwingUtilities.invokeLater(() -> {
                        appendLog("Concluído. Itens exportados:");
                        appendLog("  HTTP history (Proxy): " + stats.proxy);
                        appendLog("  WebSocket messages:   " + stats.webSocket);
                        appendLog("  Repeater:             " + stats.repeater);
                        appendLog("  Intruder:             " + stats.intruder);
                        appendLog("  Outras ferramentas:   " + stats.otherTools);
                        appendLog("  Target / Site map:    " + stats.target);
                        appendLog("  Collaborator:         " + stats.collaborator);
                        appendLog("Arquivo salvo: " + file.getAbsolutePath());
                        statusLabel.setText("Concluído: " + file.getName());
                        JOptionPane.showMessageDialog(ExporterPanel.this,
                                "Exportação concluída!\n" + file.getAbsolutePath(),
                                EXTENSION_NAME, JOptionPane.INFORMATION_MESSAGE);
                    });
                } catch (Exception ex) {
                    api.logging().logToError("Export failed: " + ex);
                    SwingUtilities.invokeLater(() -> {
                        appendLog("ERRO: " + ex.getMessage());
                        statusLabel.setText("Erro na exportação.");
                        JOptionPane.showMessageDialog(ExporterPanel.this,
                                "Erro: " + ex.getMessage(),
                                EXTENSION_NAME, JOptionPane.ERROR_MESSAGE);
                    });
                }
            }, "claude-xml-export").start();
        }

        private void appendLog(String msg) {
            SwingUtilities.invokeLater(() -> {
                logArea.append(msg + "\n");
                logArea.setCaretPosition(logArea.getDocument().getLength());
            });
        }
    }

    // ------------------------------------------------------------------
    // Options + record model
    // ------------------------------------------------------------------
    static final class ExportOptions {
        boolean proxy, webSocket, repeater, intruder, otherTools, target, collaborator;
    }

    /** A request/response captured live from a Burp tool. */
    static final class CapturedRecord {
        final long seq;
        final ToolType tool;
        final String time;
        final String method;
        final String url;
        final String host;
        volatile XmlText.Msg request;
        volatile XmlText.Msg response;
        volatile Short status;

        CapturedRecord(long seq, ToolType tool, String time, String method, String url, String host) {
            this.seq = seq;
            this.tool = tool;
            this.time = time;
            this.method = method;
            this.url = url;
            this.host = host;
        }
    }

    // ------------------------------------------------------------------
    // Live traffic collector
    // ------------------------------------------------------------------
    static final class LiveTrafficCollector implements HttpHandler {
        private final AtomicLong seq = new AtomicLong();
        private final Map<Integer, CapturedRecord> pending = new ConcurrentHashMap<>();
        private final List<CapturedRecord> records = Collections.synchronizedList(new ArrayList<>());
        private static final DateTimeFormatter ISO = DateTimeFormatter.ISO_OFFSET_DATE_TIME;

        @Override
        public RequestToBeSentAction handleHttpRequestToBeSent(HttpRequestToBeSent req) {
            try {
                ToolType tool = req.toolSource().toolType();
                // Proxy traffic is read from proxy().history() instead, to avoid duplication.
                if (tool != ToolType.PROXY) {
                    if (records.size() < MAX_LIVE_RECORDS) {
                        String host = req.httpService() != null ? req.httpService().host() : "";
                        CapturedRecord r = new CapturedRecord(
                                seq.incrementAndGet(), tool,
                                ZonedDateTime.now().format(ISO),
                                safe(req.method()), safe(req.url()), safe(host));
                        r.request = XmlExporter.msgOf(req);
                        records.add(r);
                        pending.put(req.messageId(), r);
                    }
                }
            } catch (Exception ignored) {
                // Never break Burp's traffic on capture errors.
            }
            return RequestToBeSentAction.continueWith(req);
        }

        @Override
        public ResponseReceivedAction handleHttpResponseReceived(HttpResponseReceived resp) {
            try {
                CapturedRecord r = pending.remove(resp.messageId());
                if (r != null) {
                    r.response = XmlExporter.msgOf(resp);
                    r.status = resp.statusCode();
                }
            } catch (Exception ignored) {
            }
            return ResponseReceivedAction.continueWith(resp);
        }

        List<CapturedRecord> snapshot() {
            synchronized (records) {
                return new ArrayList<>(records);
            }
        }

        void clear() {
            pending.clear();
            records.clear();
        }

        private static String safe(String s) {
            return s == null ? "" : s;
        }
    }
}
